tensorflow fundamentals

covering :
- tensors
- extracting info from tensors
- manipulating tensors
- tensors & numpy
- @tf.function (speed up your regular python functions)
- tensorflow with GPUs
- exercises


# Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Tensors dimension (ndim)
scalar.ndim

0

In [4]:
# Vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create matrix(more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [5., 7.]], dtype=tf.float16) #specify data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  7.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      
                      [[7,8,9],
                      [10,11,12]],

                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

Scalar : a single number

Vector : a number with directior

Matrix : 2 dimensional array of numbers

Tensor : n-dimensional array of nubmers

### Create tensor with `tf.Variable`


In [12]:
# create tensor with `tf.Variable()`

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, changeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#change the value/elemtnts in our changeable tensor with .assign()
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

### Create random tensor

tensors of arbitrary size contains random numbers

In [14]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order elements in the tensors


In [15]:
# shuffle a tensor(shuffle your data so the order doesnt effect learning processes)

not_shuffled = tf.constant([[10, 7],
                            [2, 5],
                            [5, 7]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 5,  7]], dtype=int32)>

In [16]:
shuffled_tensor = tf.random.shuffle(not_shuffled)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  7],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [17]:
tf.random.set_seed(42) #global level
tf.random.shuffle(not_shuffled, seed=42) #op level

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 5,  7]], dtype=int32)>

### Other way to make tensors


In [18]:
tf.ones([10,7]) # Create tensor of all ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
tf.zeros([5,7]) #tensor of all zeroes

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### NumPy array to Tensors

whats the difference, tensors can be run on GPU, the rest pretty much the same

In [20]:
# Turning numpy array to tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #numpy array 1 to 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A = tf.constant(numpy_A, shape = (3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from our tensors

be aware of following tensors attributes:
- Shape
- Rank
- Dimension
- Size

In [22]:
# Rank 4 tensors (4 dimensions)

rank_4_tensors = tf.zeros(shape=[2, 3 ,4 ,5])
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensors[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
rank_4_tensors.shape, rank_4_tensors.ndim, tf.size(rank_4_tensors)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
# Get attributes from tensor

print("Datatype of each elements:", rank_4_tensors.dtype)
print("Number of dimension (rank):", rank_4_tensors.ndim)
print("shape of tensors:", rank_4_tensors.shape)
print("elements on first axis:", rank_4_tensors.shape[0])
print("total number of elements in our tensor:", tf.size(rank_4_tensors))

Datatype of each elements: <dtype: 'float32'>
Number of dimension (rank): 4
shape of tensors: (2, 3, 4, 5)
elements on first axis: 2
total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


# Indexing Tensors

Just like python lists

In [26]:
# Python list
somelist = [1, 2, 3, 4]
somelist[:2]

[1, 2]

In [27]:
# Get the first 2 elements of each dimension
rank_4_tensors[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# get first element from each dimension except the final one
rank_4_tensors[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
# create rank 2 tensor
rank_2_tensor = tf.constant([[5,7],
                             [6,9]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [30]:
# get last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

In [31]:
# Add extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # "..." rather than explicitly wrting ":, :, :"
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [7]],

       [[6],
        [9]]], dtype=int32)>

In [32]:
# Another way to add dimension
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [7]],

       [[6],
        [9]]], dtype=int32)>

In [33]:
tf.expand_dims(rank_2_tensor, axis=0) #"0" expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 7],
        [6, 9]]], dtype=int32)>

In [34]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [6, 9]], dtype=int32)>

# Manipulating Tensor

**Basic operations**

add, subtract, multiply, divide

In [35]:
# Add
tensor = tf.constant([[6,9], [4,2]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 19],
       [14, 12]], dtype=int32)>

In [36]:
# Substract
tensor - 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 1, -1]], dtype=int32)>

In [37]:
# Multiplication
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 18],
       [ 8,  4]], dtype=int32)>

In [38]:
# Divide
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3. , 4.5],
       [2. , 1. ]])>

Built-in tensor function

In [39]:
tf.multiply(tensor, 2) #can utilize GPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 18],
       [ 8,  4]], dtype=int32)>

## Matrix Multiplication

matmul is the most common tensor op

matmul rules :
1. Matching inner dimensions
2. result has shape of outer dimension

In [40]:
#Matrix mutiplication in tensor
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[72, 72],
       [32, 40]], dtype=int32)>

In [41]:
tensor * tensor # element wise not matmul use "@" instead

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[36, 81],
       [16,  4]], dtype=int32)>

In [42]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[72, 72],
       [32, 40]], dtype=int32)>

In [43]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 9],
        [4, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 9],
        [4, 2]], dtype=int32)>)

In [44]:
#Create 2 (3, 2) tensor

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [45]:
X @ Y
# will cause error, each matrices inner dimension not matching, reshape or transpose either matrices to make it work
# (3,2) @ (3,2) | 3=/=2

InvalidArgumentError: ignored

In [46]:
# Reshape Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [47]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [48]:
# X @ Y =/= Y @ X
tf.reshape(Y, shape=(2, 3)) @ X
#different dimension result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]], dtype=int32)>

In [49]:
#transpose, transpose flip the axis
Y, tf.transpose(Y), tf.reshape(Y, shape=(2, 3))


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [50]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

** Dot Product**

matmul is also referred as dot product

matmul can be done using :
- `tf.matmul()`
- `tf.tensordot()`

In [51]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [52]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [53]:
#perform matrix multiplication X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [54]:
#same but reshaped Y
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

# Changing datatype of a tensor

In [55]:
# Create a new tensor with default datatype
B = tf.constant([4.2, 6.9])
B.dtype

tf.float32

In [56]:
C = tf.constant([420, 69])
C.dtype

tf.int32

In [57]:
#reduce precision, from 32bits to 16bits
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4.2, 6.9], dtype=float16)>,
 tf.float16)

In [58]:
E = tf.cast(C, dtype = tf.float32)
E = tf.cast(E, dtype = tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([420.,  69.], dtype=float16)>

# Aggregating Tensor

In [59]:
D = tf.constant([-6, -9])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-6, -9], dtype=int32)>

In [60]:
#Get absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 9], dtype=int32)>

- Get Minimum
- Get Maximum
- Get Mean
- Get Sum

In [61]:
F = tf.constant(np.random.randint(0, 100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 9, 97, 17, 47, 47, 16, 87, 13, 84, 78, 27, 79, 35, 15, 75, 12, 82,
       54, 14, 43,  4, 79, 88, 88, 63, 30, 24, 86, 97, 68, 57, 62, 53, 82,
       38, 91, 57, 54, 45, 73, 45, 27, 83, 39, 99, 21, 87,  8, 37, 19])>

In [62]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [63]:
#Find Min and Max
tf.reduce_min(F), tf.reduce_max(F)


(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>)

In [64]:
#Find Mean
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [65]:
#Find Sum
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2635>

In [66]:
#Find Variance and stdev
import tensorflow_probability as tfp
tfp.stats.variance(F), tfp.stats.stddev(tf.cast(F, dtype = tf.float32))

(<tf.Tensor: shape=(), dtype=int64, numpy=832>,
 <tf.Tensor: shape=(), dtype=float32, numpy=28.84389>)

In [67]:
tf.math.reduce_variance(tf.cast(F, dtype = tf.float32)), tf.math.reduce_std(tf.cast(F, dtype = tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=831.97>,
 <tf.Tensor: shape=(), dtype=float32, numpy=28.84389>)

# Find positional maximum and minimum of a tensor

In [68]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=[42])
G

<tf.Tensor: shape=(42,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 ], dtype=float32)>

In [69]:
#Find min and max position
tf.argmax(G), tf.argmin(G)

(<tf.Tensor: shape=(), dtype=int64, numpy=30>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [70]:
#Value in that index/position
G[tf.argmax(G)], G[tf.argmin(G)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9485276>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing tensor (removing single dimensions)

In [71]:
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [72]:
squeezed_H = tf.squeeze(H)
squeezed_H, squeezed_H.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

# One-Hot Encoding

In [73]:
somelist2=[0,1,2] # Could represent anything, Red, Green, Blue

tf.one_hot(somelist2, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [74]:
tf.one_hot(somelist2, depth=3, on_value='bruh', off_value='yeet')

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'bruh', b'yeet', b'yeet'],
       [b'yeet', b'bruh', b'yeet'],
       [b'yeet', b'yeet', b'bruh']], dtype=object)>

# More operations

In [75]:
I = tf.range(1, 10)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [77]:
tf.sqrt(tf.cast(I, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [78]:
tf.math.log(tf.cast(I, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy

Tensor interacts beautifully with NumPy arrays

In [79]:
J = tf.constant(np.array([3., 7., 9.]))
J, J.dtype

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 7., 9.])>, tf.float64)

In [80]:
#convert tensor to numpy array
np.array(J), type(np.array(J))

(array([3., 7., 9.]), numpy.ndarray)

In [81]:
J.numpy(), type(J.numpy())

(array([3., 7., 9.]), numpy.ndarray)

In [82]:
J.numpy().dtype

dtype('float64')

In [83]:
J[1]

<tf.Tensor: shape=(), dtype=float64, numpy=7.0>

In [84]:
numpy_J = tf.constant(np.array([3., 6., 9.]))
tensor_J = tf.constant([3.,6.,9.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Accessing GPU

In [85]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [86]:
!nvidia-smi

Thu May 20 05:10:59 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    26W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If you have cuda enabled GPU, tensorflow will automatically use it whenever possible

excercises

In [96]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]
randotensor1 = tf.random.uniform(shape=([5,300]), minval=0, maxval=1)
randotensor2 = tf.random.uniform(shape=([5,300]), minval=0, maxval=1)
randotensor1, randotensor2, randotensor1==randotensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936875, 0.19861352, 0.9481231 , ..., 0.3573054 , 0.13161755,
         0.22565222]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
         0.7110305 ],
        [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
         0.06227863],
        [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
         0.44452012],
        [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
         0.47421408],
        [0.26160

In [98]:
tf.matmul(randotensor1, tf.reshape(randotensor2, shape=([300,5])))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.32888 , 78.12473 , 71.479805, 73.525024, 77.99086 ],
       [75.88234 , 82.679   , 73.4152  , 76.83804 , 76.71848 ],
       [72.659355, 77.51954 , 69.93235 , 75.032875, 73.92935 ],
       [75.051926, 81.31821 , 73.18502 , 79.829384, 75.11594 ],
       [76.083176, 77.63467 , 73.55354 , 75.60354 , 73.19452 ]],
      dtype=float32)>

In [102]:
tf.tensordot(randotensor1, tf.reshape(randotensor2, shape=([300,5])), axes=1)

InvalidArgumentError: ignored

In [101]:
tf.matmul(randotensor1, tf.reshape(randotensor2, shape=([300,5])))==tf.tensordot(randotensor1, tf.reshape(randotensor2, shape=([300,5])), axes=1)

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [149]:
randotensor3 = tf.random.uniform(shape=([224,224,3]), minval=0, maxval=1)
randotensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6208451 , 0.35142744, 0.3399557 ],
        [0.5266949 , 0.27369344, 0.77060723],
        [0.19219303, 0.8650671 , 0.4890945 ],
        ...,
        [0.1339755 , 0.39838994, 0.3509227 ],
        [0.8829664 , 0.6942359 , 0.02672243],
        [0.26134396, 0.6343547 , 0.9801271 ]],

       [[0.6546608 , 0.9848912 , 0.04705787],
        [0.49374986, 0.88043225, 0.53859603],
        [0.6660409 , 0.4169606 , 0.6165247 ],
        ...,
        [0.82807016, 0.07065547, 0.00150406],
        [0.02727604, 0.6475557 , 0.6783521 ],
        [0.01863849, 0.9219259 , 0.00386262]],

       [[0.5400611 , 0.08981514, 0.99444294],
        [0.85332155, 0.539261  , 0.5117184 ],
        [0.8415967 , 0.5161035 , 0.7921139 ],
        ...,
        [0.5732502 , 0.88516665, 0.72878873],
        [0.02949047, 0.8549316 , 0.41315794],
        [0.35604417, 0.9215387 , 0.74590814]],

       ...,

       [[0.74267006, 0.7796637 , 0.3875823 ],
        [0.46

In [187]:
tf.argmin(randotensor3[0]), tf.argmax(randotensor3[0])

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([153, 162,  93])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 74, 150, 136])>)

In [152]:
randotensor3[153, 162]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.24808943, 0.26639748, 0.23349357], dtype=float32)>

In [171]:
randotensor4 = tf.random.uniform(shape=([4,4,3]), minval=0, maxval=1)
randotensor4

<tf.Tensor: shape=(4, 4, 3), dtype=float32, numpy=
array([[[0.5852475 , 0.9927181 , 0.3110503 ],
        [0.44591808, 0.8970233 , 0.6452199 ],
        [0.04707861, 0.43374014, 0.6919069 ],
        [0.2356894 , 0.54439366, 0.45189762]],

       [[0.8827189 , 0.5912421 , 0.5673742 ],
        [0.39240313, 0.1258322 , 0.94337356],
        [0.19854975, 0.45738494, 0.5995703 ],
        [0.2941928 , 0.7386502 , 0.05998945]],

       [[0.12787127, 0.6411879 , 0.4465276 ],
        [0.22277546, 0.12308025, 0.7215545 ],
        [0.2790836 , 0.27117848, 0.32610834],
        [0.60007644, 0.84208965, 0.65200114]],

       [[0.8364419 , 0.5823555 , 0.7090963 ],
        [0.23557973, 0.17463195, 0.04684031],
        [0.03135979, 0.9831356 , 0.9527756 ],
        [0.1761508 , 0.98687565, 0.03847897]]], dtype=float32)>

In [176]:
tf.argmin(randotensor4[0])

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 0])>

In [178]:
randotensor4[([2,2,0])]

<tf.Tensor: shape=(), dtype=float32, numpy=0.2790836>

In [179]:
randotensor5 = tf.random.uniform(shape=([1, 224, 224, 3]), minval=0, maxval=1)
randotensor5 = tf.squeeze(randotensor5)

In [182]:
randotensor6 = tf.random.uniform(shape=([10]), minval=0, maxval=10, dtype=tf.int32)
randotensor6

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 1, 3, 1, 3, 7, 4, 2, 5, 5], dtype=int32)>

In [185]:
randotensor6[tf.argmax(randotensor6)]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [189]:
tf.one_hot(randotensor6, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>